databases:
  - name: cogi_photo_db
    databaseName: cogi_photo_db
    user: cogi_photo
    region: singapore

services:
  - type: web
    name: cogi_photo
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cogi_photo_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
